### ISSUE TITLE
Screen blinking / slow image assembly speed

### ISSUE THREAD

**Issue by nsamarkus** [Gabbajoe/spotipi-eink#4]
Hi there,
it seems that you are still updating this project.
I put the 5.7 inch together and it seems that the screen blinks for about 27 seconds while assembling the image on the screen. Is that normal or is there something wrong with mine?
Just trying to see if something got screwed up that I am not being able to find.
Couldn't find an email address for you, so I am posting here.
Thank you.

**Comment by Gabbajoe** [comment]
Hi @nsamarkus the refresh time is normal if you checkout https://shop.pimoroni.com/products/inky-impression-5-7?variant=32298701324371 they write there: 

>Please note that Inky Impression takes around 30 seconds to refresh the screen, so is best suited to projects that don't rely on constant screen updates.

I currently play around with some tweaks to the library from Pimoroni as they have hard coded sleeps in it and do not use the busy state from the screens controller.

**Comment by nsamarkus** [comment]
Totally missed that on the product page. My bad. First time that I used a color e-ink. Just wanted to make sure something didn't get messed up. Thanks for the response. :)
