### ISSUE TITLE
How to run the program?

### ISSUE THREAD

**Issue by tanzhijir-04** [Gabbajoe/spotipi-eink#6]
**I gonna run this on LCD screen through HDMI output on my zero 2W, I have 2 questions:

1. when I set the redirect URL, "http://loacalhost/redirect",the localhost should be replaced with my real IP?
2. after I finish install spotipi.service, nothing just happend, I know this program should be running in web browser, but what should i do to run the program?**

---

![after installing, nothing happened](https://github.com/Gabbajoe/spotipi-eink/assets/149170904/d43bc38b-b05c-4553-9b72-7749d07c285b)

**Comment by Gabbajoe** [comment]
Hi this project do not support s XServer Based LCD screen. it only support the eInk Screen connect to the SPI interface. What you can do you can use the project from the branch og-repo link https://github.com/Gabbajoe/spotipi-eink/tree/og-repo and then open with the browser the file "~/spotipi-eink/python/client/spotipi-eink.html"

**Comment by Gabbajoe** [comment]
closing this "issue" as LCDs are not supported.
