### ISSUE TITLE
LCD

### ISSUE THREAD

**Issue by skylarrgrey** [Gabbajoe/spotipi-eink#7]
Hi there,

Would this be able to be modified to run via HDMI to an LCD screen as I want to build it into a picture frame ?

Many thanks

**Comment by Gabbajoe** [comment]
Hi,
this program is creating a PNG and then using then  SPI interface to sent the PNG to the eInk screens. This is not a X application. You could work a round this by using a picture viewer in a desktop environment to display the PNG and reload is once it got updated. You free to fork or copy this project to adjust it to your needs.

Cheers,
Gabbajoe
